In [86]:
import pandas as pd
import openpyxl as xl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [22]:
boe_tape = pd.read_excel('/Users/andrewmcclymont/PycharmProjects/PythonProject/data/RMBS_Model/BOE_DataTape.xlsx')

#Want to drop the AR row
boe_tape = boe_tape[1:]

In [23]:
boe_tape.head()

,Pool Cut-off Date,Pool Identifier,Loan Identifier,Regulated Loan,Originator,Servicer Identifier,Borrower Identifier,Property Identifier,Blank,Blank.1,...,Bureau Krediet Registratie 1 to 10 - Number of Months Since Cured (Secondary Borrower - At Origination),Bureau Score Provider (Secondary Borrower - At Origination),Bureau Score Type (Secondary Borrower - At Origination),Bureau Score Value (Secondary Borrower - At Origination),Borrower Type (Secondary Borrower),Foreign National (Secondary Borrower),Borrower Credit Quality (Secondary Borrower),First-time Buyer (Secondary Borrower),Bankruptcy or Individual Voluntary Arrangement Flag.1,Bankruptcy or Individual Voluntary Arrangement Flag (Second Borrower).1
1,31-05-2025,Finsbury Square 21-2,9100006288,Y,Kensington Mortgages,Kensington Mortgage Company,9100006288,9100006288,NaN,NaN,...,NaN,ND,ND,ND,ND,ND,ND,ND,N,ND
2,31-05-2025,Finsbury Square 21-2,9100008835,Y,Kensington Mortgages,Kensington Mortgage Company,9100008835,9100008835,NaN,NaN,...,NaN,ND,ND,ND,ND,ND,ND,ND,N,ND
3,31-05-2025,Finsbury Square 21-2,9100009832,Y,Kensington Mortgages,Kensington Mortgage Company,9100009832,9100009832,NaN,NaN,...,NaN,ND,ND,ND,ND,ND,ND,ND,N,ND
4,31-05-2025,Finsbury Square 21-2,9100011667,N,Kensington Mortgages,Kensington Mortgage Company,9100011667,9100011667,NaN,NaN,...,NaN,3,8,505,IND,N,ND,ND,N,N
5,31-05-2025,Finsbury Square 21-2,9100011981,Y,Kensington Mortgages,Kensington Mortgage Company,9100011981,9100011981,NaN,NaN,...,NaN,ND,ND,ND,ND,ND,ND,ND,N,ND

**Want to clean the column naming to make it easier to call later**

In [37]:
# import importlib
# import sys
#
# # Remove the module from cache if it exists
# if 'src.utils.strings' in sys.modules:
#     del sys.modules['src.utils.strings']
#
# # Try to import the module itself
# try:
#     from src.utils import strings
#     print("Module imported successfully!")
#     print("\nAvailable functions:")
#     print([name for name in dir(strings) if not name.startswith('_')])
# except Exception as e:
#     print(f"Error importing module: {e}")
#     import traceback
#     traceback.print_exc()

Module imported successfully!

Available functions:
['clean_text', 'examples', 'pd', 'result', 's']

In [101]:
#Run data cleaning on this first
from src.utils.strings import clean_to_snake_case

#Clean the naming of the columns
boe_tape.columns = [clean_to_snake_case(col) for col in boe_tape.columns]

#Clean the columns to be camel_case
boe_tape.head()

,pool_cut_off_date,pool_identifier,loan_identifier,regulated_loan,originator,servicer_identifier,borrower_identifier,property_identifier,blank,blank_1,...,borrower_type_secondary_borrower,foreign_national_secondary_borrower,borrower_credit_quality_secondary_borrower,first_time_buyer_secondary_borrower,bankruptcy_or_individual_voluntary_arrangement_flag_1,bankruptcy_or_individual_voluntary_arrangement_flag_second_borrower_1,repayment_method_mapped,interest_rate_type_mapped,current_interest_rate_index_mapped,maturity_quarter
1,31-05-2025,Finsbury Square 21-2,9100006288,Y,Kensington Mortgages,Kensington Mortgage Company,9100006288,9100006288,NaN,NaN,...,ND,ND,ND,ND,N,ND,repayment,floating,SVR,Q3
2,31-05-2025,Finsbury Square 21-2,9100008835,Y,Kensington Mortgages,Kensington Mortgage Company,9100008835,9100008835,NaN,NaN,...,ND,ND,ND,ND,N,ND,repayment,fix_to_float,SVR,Q2
3,31-05-2025,Finsbury Square 21-2,9100009832,Y,Kensington Mortgages,Kensington Mortgage Company,9100009832,9100009832,NaN,NaN,...,ND,ND,ND,ND,N,ND,interest_only,fix_to_float,SVR,Q2
4,31-05-2025,Finsbury Square 21-2,9100011667,N,Kensington Mortgages,Kensington Mortgage Company,9100011667,9100011667,NaN,NaN,...,IND,N,ND,ND,N,N,interest_only,fix_to_float,SVR,Q2
5,31-05-2025,Finsbury Square 21-2,9100011981,Y,Kensington Mortgages,Kensington Mortgage Company,9100011981,9100011981,NaN,NaN,...,ND,ND,ND,ND,N,ND,interest_only,fix_to_float,SVR,Q2

In [45]:
boe_tape.columns.to_list()

['pool_cut_off_date',
 'pool_identifier',
 'loan_identifier',
 'regulated_loan',
 'originator',
 'servicer_identifier',
 'borrower_identifier',
 'property_identifier',
 'blank',
 'blank_1',
 'blank_2',
 'blank_3',
 'blank_4',
 'blank_5',
 'borrower_type',
 'foreign_national',
 'borrower_credit_quality',
 'borrower_year_of_birth',
 'number_of_debtors',
 'second_applicant_year_of_birth',
 'borrowers_employment_status',
 'first_time_buyer',
 'right_to_buy',
 'right_to_buy_price',
 'class_of_borrower',
 'primary_income',
 'income_verification_for_primary_income',
 'secondary_income',
 'income_verification_for_secondary_income',
 'resident',
 'number_of_county_court_judgements_or_equivalent_satisfied',
 'value_of_county_court_judgements_or_equivalent_satisfied',
 'number_of_county_court_judgements_or_equivalent_unsatisfied',
 'value_of_county_court_judgements_or_equivalent_unsatisfied',
 'last_county_court_judgements_or_equivalent_date',
 'bankruptcy_or_individual_voluntary_arrangement_flag',
 'bureau_krediet_registratie_1_to_10_credit_type',
 'bureau_krediet_registratie_1_to_10_registration_date',
 'bureau_krediet_registratie_1_to_10_arrears_code',
 'bureau_krediet_registratie_1_to_10_credit_amount',
 'bureau_krediet_registratie_1_to_10_is_coding_cured',
 'bureau_krediet_registratie_1_to_10_number_of_months_since_cured',
 'bureau_score_provider',
 'bureau_score_type',
 'bureau_score_date',
 'bureau_score_value',
 'prior_repossessions',
 'previous_mortgage_arrears_0_6_months',
 'previous_mortgage_arrears_6_months',
 'internal_rating',
 'blank_6',
 'blank_7',
 'blank_8',
 'blank_9',
 'loan_origination_date',
 'date_of_loan_maturity',
 'account_status_date',
 'origination_channel_arranging_bank_or_division',
 'purpose',
 'shared_ownership',
 'loan_term',
 'principal_grace_period',
 'amount_guaranteed',
 'subsidy',
 'loan_currency_denomination',
 'original_balance',
 'current_balance',
 'fractioned_subrogated_loans',
 'repayment_method',
 'payment_frequency',
 'payment_due',
 'payment_type',
 'debt_to_income',
 'type_of_guarantee_provider',
 'guarantee_provider',
 'income_guarantor',
 'subsidy_received',
 'mortgage_indemnity_guarantee_provider',
 'mortgage_indemnity_guarantee_attachment_point',
 'prior_balances',
 'other_prior_balances',
 'pari_passu_loans',
 'subordinated_claims',
 'lien',
 'retained_amount',
 'retained_amount_date',
 'maximum_balance',
 'further_loan_advance',
 'further_loan_advance_date',
 'flexible_loan_amount',
 'further_advances',
 'length_of_payment_holiday',
 'subsidy_period',
 'mortgage_inscription',
 'mortgage_mandate',
 'deed_of_postponement',
 'pre_payment_amount',
 'pre_payment_date',
 'pre_payment_penalties',
 'cumulative_pre_payments',
 'amount_of_pre_payments_allowed_per_year',
 'offset_savings_balance',
 'original_percentage_owned',
 'current_percentage_owned',
 'help_to_buy_scheme_type',
 'blank_10',
 'interest_rate_type',
 'current_interest_rate_index',
 'current_interest_rate',
 'current_interest_rate_margin',
 'interest_rate_reset_interval',
 'interest_cap_rate',
 'interest_revision_date_1',
 'revision_margin_2',
 'interest_revision_date_2',
 'revision_margin_3',
 'interest_revision_date_3',
 'revised_interest_rate_index',
 'revised_interest_rate_margin',
 'final_margin',
 'final_step_date',
 'restructuring_arrangement',
 'forbearance_type',
 'blank_11',
 'blank_12',
 'blank_13',
 'blank_14',
 'geographic_region',
 'property_postcode',
 'occupancy_type',
 'property_type',
 'new_property',
 'construction_year',
 'property_rating',
 'original_loan_to_value',
 'valuation_amount',
 'original_valuation_type',
 'valuation_date',
 'confidence_interval_for_original_automated_valuation_model_valuation',
 'provider_of_original_automated_valuation_model_valuation',
 'current_loan_to_value',
 'purchase_price',
 'current_valuation_amount',
 'current_valuation_type',
 'current_valuation_date',
 'confidence_interval_for_current_automated_valuation_model_valuation',
 'provider_of_current_automated_valuation_model_valuation',
 'property_value_at_time_of_latest_loan_advance',
 'indexed_foreclosure_value',
 'ipoteca',
 'date_of_sale',
 'additional_collateral',
 'additional_collateral_provider',
 'gross_annual_rental_income',
 'number_of_buy_to_let_properties',
 'debt_service_coverage_ratio',
 'additional_collateral_value',
 'real_estate_owned',
 'is_property_transferability_limited',
 'time_until_declassification',
 'blank_15',
 'current_energy_performance_certificate_value',
 'potential_energy_performance_certificate_value',
 'exemption_from_energy_efficiency_regulation',
 'blank_16',
 'account_status',
 'date_last_current',
 'date_last_in_arrears',
 'arrears_balance',
 'number_months_in_arrears',
 'arrears_1_month_ago',
 'arrears_2_months_ago',
 'performance_arrangement',
 'litigation',
 'redemption_date',
 'months_in_arrears_prior',
 'default_or_foreclosure',
 'date_of_default',
 'sale_price',
 'loss_on_sale',
 'cumulative_recoveries',
 'professional_negligence_recoveries',
 'loan_flagged_as_contencioso',
 'blank_17',
 'blank_18',
 'blank_19',
 'blank_20',
 'blank_21',
 'second_borrowers_employment_status',
 'class_of_second_borrower',
 'resident_second_borrower',
 'number_of_county_court_judgements_or_equivalent_satisfied_second_borrower',
 'value_of_county_court_judgements_or_equivalent_satisfied_second_borrower',
 'number_of_county_court_judgements_or_equivalent_unsatisfied_second_borrower',
 'value_of_county_court_judgements_or_equivalent_unsatisfied_second_borrower',
 'last_county_court_judgements_or_equivalent_date_second_borrower',
 'bankruptcy_or_individual_voluntary_arrangement_flag_second_borrower',
 'bureau_krediet_registratie_1_to_10_credit_type_second_borrower',
 'bureau_krediet_registratie_1_to_10_registration_date_second_borrower',
 'bureau_krediet_registratie_1_to_10_arrears_code_second_borrower',
 'bureau_krediet_registratie_1_to_10_credit_amount_second_borrower',
 'bureau_krediet_registratie_1_to_10_is_coding_cured_second_borrower',
 'bureau_krediet_registratie_1_to_10_number_of_months_since_cured_second_borrower',
 'bureau_score_provider_second_borrower',
 'bureau_score_type_second_borrower',
 'bureau_score_date_second_borrower',
 'bureau_score_value_second_borrower',
 'prior_repossessions_second_borrower',
 'previous_mortgage_arrears_0_6_months_second_borrower',
 'previous_mortgage_arrears_6_months_second_borrower',
 'bureau_krediet_registratie_1_to_10_credit_type_primary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_arrears_code_primary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_credit_amount_primary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_is_coding_cured_primary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_number_of_months_since_cured_primary_borrower_at_origination',
 'bureau_score_provider_primary_borrower_at_origination',
 'bureau_score_type_primary_borrower_at_origination',
 'bureau_score_value_primary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_credit_type_secondary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_registration_date_secondary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_arrears_code_secondary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_credit_amount_secondary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_is_coding_cured_secondary_borrower_at_origination',
 'bureau_krediet_registratie_1_to_10_number_of_months_since_cured_secondary_borrower_at_origination',
 'bureau_score_provider_secondary_borrower_at_origination',
 'bureau_score_type_secondary_borrower_at_origination',
 'bureau_score_value_secondary_borrower_at_origination',
 'borrower_type_secondary_borrower',
 'foreign_national_secondary_borrower',
 'borrower_credit_quality_secondary_borrower',
 'first_time_buyer_secondary_borrower',
 'bankruptcy_or_individual_voluntary_arrangement_flag_1',
 'bankruptcy_or_individual_voluntary_arrangement_flag_second_borrower_1']

**Will make some summary stats - simular to the model** (Not an EDA excercise yet)
* Pool cut of date
* Number of loans
* Stats on the loan list

In [58]:
# Checks that all loans have balance, gt 0 or lt 0
# boe_tape['current_balance'].info()
# print(boe_tape[('current_balance')].isnull().sum())
print(f'Number of loans gt 0  is {boe_tape[(boe_tape['current_balance'] > 0)].shape[0]}')


#Cut of date
# print(f'Pool cut of ates is {boe_tape[boe_tape['pool_cut_off_date']].()}')

Number of loans gt 0  is 732

**BOE Extract: Will apply the yaml mapping for:**
* Repayment methods overview (need to create a mapping table)
* Interest Type mappping overview
* Index mapping overview

In [72]:
#Mapping the data for repayment
from src.utils.boe_extract_mapping import load_boe_mapping
from src.utils.boe_extract_mapping import apply_boe_mapping

mappings = load_boe_mapping("/Users/andrewmcclymont/PycharmProjects/PythonProject/European_RMBS_Model/Config/Mappings.yaml")

# Define which DataFrame column uses which YAML mapping
column_mapping = {
    "repayment_method": "repayment_method",
    "interest_rate_type": "interest_type",
    "current_interest_rate_index": "index_mapping"
}
# Apply mapping
boe_tape = apply_boe_mapping(df=boe_tape,column_mapping=column_mapping,mappings=mappings,default_value=999)
boe_tape.head()

,pool_cut_off_date,pool_identifier,loan_identifier,regulated_loan,originator,servicer_identifier,borrower_identifier,property_identifier,blank,blank_1,...,bureau_score_value_secondary_borrower_at_origination,borrower_type_secondary_borrower,foreign_national_secondary_borrower,borrower_credit_quality_secondary_borrower,first_time_buyer_secondary_borrower,bankruptcy_or_individual_voluntary_arrangement_flag_1,bankruptcy_or_individual_voluntary_arrangement_flag_second_borrower_1,repayment_method_mapped,interest_rate_type_mapped,current_interest_rate_index_mapped
1,31-05-2025,Finsbury Square 21-2,9100006288,Y,Kensington Mortgages,Kensington Mortgage Company,9100006288,9100006288,NaN,NaN,...,ND,ND,ND,ND,ND,N,ND,repayment,floating,SVR
2,31-05-2025,Finsbury Square 21-2,9100008835,Y,Kensington Mortgages,Kensington Mortgage Company,9100008835,9100008835,NaN,NaN,...,ND,ND,ND,ND,ND,N,ND,repayment,fix_to_float,SVR
3,31-05-2025,Finsbury Square 21-2,9100009832,Y,Kensington Mortgages,Kensington Mortgage Company,9100009832,9100009832,NaN,NaN,...,ND,ND,ND,ND,ND,N,ND,interest_only,fix_to_float,SVR
4,31-05-2025,Finsbury Square 21-2,9100011667,N,Kensington Mortgages,Kensington Mortgage Company,9100011667,9100011667,NaN,NaN,...,505,IND,N,ND,ND,N,N,interest_only,fix_to_float,SVR
5,31-05-2025,Finsbury Square 21-2,9100011981,Y,Kensington Mortgages,Kensington Mortgage Company,9100011981,9100011981,NaN,NaN,...,ND,ND,ND,ND,ND,N,ND,interest_only,fix_to_float,SVR

In [144]:
# Updating the logic to overwrite the part and part with grace period logic:
mask = (boe_tape['repayment_method_mapped'] == "part_and_part") & (boe_tape['principal_grace_period'] == "ND")
boe_tape.loc[mask, 'repayment_method_mapped'] = "repayment"

# Updating the logic to other with svr
mask = (boe_tape['current_interest_rate_index_mapped'] == "other")
boe_tape.loc[mask, 'current_interest_rate_index_mapped'] = "SVR"

In [ ]:
#Calculate the implied SVR
def implied_svr(df, interest_type_col, curr_interest_rate_col, interest_rate_margin_col):
    # Use np.where to vectorize the logic
    return np.where(
        df[interest_type_col] == "floating",
        df[curr_interest_rate_col] - df[interest_rate_margin_col],
        np.nan
    )


boe_tape['implied_svr'] = implied_svr(boe_tape,interest_type_col='interest_rate_type_mapped',curr_interest_rate_col="current_interest_rate",interest_rate_margin_col="current_interest_rate_margin")
print(boe_tape['implied_svr'])

1       0.045
2         NaN
3         NaN
4         NaN
5         NaN
        ...
728       NaN
729       NaN
730     0.045
731    0.0435
732     0.045
Name: implied_svr, Length: 732, dtype: object

In [153]:
#Need to add some columns
from src.utils.date_functions import parse_date_columns_from_string

#Quarter (stored as Q3-xx)
boe_tape['maturity_quarter'] = boe_tape['date_of_loan_maturity'].str[:2]

#update all the dataframe for dates:
boe_tape = parse_date_columns_from_string(boe_tape, columns=['date_of_loan_maturity','pool_cut_off_date','interest_revision_date_1'], region="UK", day_of_month="end",change_all_day_of_month=False, suffix="_date_converted")

# pool_cut_off = boe_tape['pool_cut_off_date_date_converted'].drop_duplicates()
boe_tape['remaining_term'] = ((boe_tape['date_of_loan_maturity_date_converted'].dt.year - boe_tape['pool_cut_off_date_date_converted'].dt.year) * 12
    + (boe_tape['date_of_loan_maturity_date_converted'].dt.month - boe_tape['pool_cut_off_date_date_converted'].dt.month))


boe_tape['reversion_term'] = ((boe_tape['date_of_loan_maturity_date_converted'].dt.year - boe_tape['pool_cut_off_date_date_converted'].dt.year) * 12
    + (boe_tape['date_of_loan_maturity_date_converted'].dt.month - boe_tape['pool_cut_off_date_date_converted'].dt.month))


boe_tape['reversion_term'] = ((boe_tape['interest_revision_date_1_date_converted'].dt.year - boe_tape['pool_cut_off_date_date_converted'].dt.year) * 12+ (boe_tape['interest_revision_date_1_date_converted'].dt.month - boe_tape['pool_cut_off_date_date_converted'].dt.month))

boe_tape.head()

,pool_cut_off_date,pool_identifier,loan_identifier,regulated_loan,originator,servicer_identifier,borrower_identifier,property_identifier,blank,blank_1,...,interest_rate_type_mapped,current_interest_rate_index_mapped,maturity_quarter,date_of_loan_maturity_date_converted,pool_cut_off_date_date_converted,remaining_term,impiled_svr,implied_svr,interest_revision_date_1_date_converted,reversion_term
1,31-05-2025,Finsbury Square 21-2,9100006288,Y,Kensington Mortgages,Kensington Mortgage Company,9100006288,9100006288,NaN,NaN,...,floating,SVR,Q3,2039-09-30,2025-05-31,172,NaN,0.045,NaT,NaN
2,31-05-2025,Finsbury Square 21-2,9100008835,Y,Kensington Mortgages,Kensington Mortgage Company,9100008835,9100008835,NaN,NaN,...,fix_to_float,SVR,Q2,2051-06-30,2025-05-31,313,NaN,NaN,2026-01-01,8.0
3,31-05-2025,Finsbury Square 21-2,9100009832,Y,Kensington Mortgages,Kensington Mortgage Company,9100009832,9100009832,NaN,NaN,...,fix_to_float,SVR,Q2,2038-06-30,2025-05-31,157,NaN,NaN,2026-07-01,14.0
4,31-05-2025,Finsbury Square 21-2,9100011667,N,Kensington Mortgages,Kensington Mortgage Company,9100011667,9100011667,NaN,NaN,...,fix_to_float,SVR,Q2,2046-06-30,2025-05-31,253,NaN,NaN,2026-07-01,14.0
5,31-05-2025,Finsbury Square 21-2,9100011981,Y,Kensington Mortgages,Kensington Mortgage Company,9100011981,9100011981,NaN,NaN,...,fix_to_float,SVR,Q2,2046-06-30,2025-05-31,253,NaN,NaN,2026-06-01,13.0

In [159]:
columns_order = [
    "loan_identifier",
    "loan_term",
    "date_of_loan_maturity",
    "maturity_quarter",
    "date_of_loan_maturity_date_converted",
    "remaining_term",
    "current_balance",
    "repayment_method",
    "repayment_method_mapped",
    "payment_due",
    "interest_rate_type",
    "interest_rate_type_mapped",
    "current_interest_rate_index",
    "current_interest_rate_index_mapped",
    "current_interest_rate",
    "current_interest_rate_margin",
    "implied_svr",
    "interest_revision_date_1_date_converted",
    "reversion_term"
]

boe_extract = boe_tape[columns_order]
boe_extract.head()

,loan_identifier,loan_term,date_of_loan_maturity,maturity_quarter,date_of_loan_maturity_date_converted,remaining_term,current_balance,repayment_method,repayment_method_mapped,payment_due,interest_rate_type,interest_rate_type_mapped,current_interest_rate_index,current_interest_rate_index_mapped,current_interest_rate,current_interest_rate_margin,implied_svr,interest_revision_date_1_date_converted,reversion_term
1,9100006288,216,Q3-2039,Q3,2039-09-30,172,40130.3,2,repayment,436.57,1,floating,11,SVR,0.098,0.053,0.045,NaT,NaN
2,9100008835,360,Q2-2051,Q2,2051-06-30,313,51353.89,2,repayment,359.75,5,fix_to_float,11,SVR,0.0705,0.033,NaN,2026-01-01,8.0
3,9100009832,204,Q2-2038,Q2,2038-06-30,157,438367.46,1,interest_only,1440,5,fix_to_float,11,SVR,0.0394,0.0374,NaN,2026-07-01,14.0
4,9100011667,300,Q2-2046,Q2,2046-06-30,253,246758.22,1,interest_only,776.16,5,fix_to_float,11,SVR,0.0379,0.0359,NaN,2026-07-01,14.0
5,9100011981,300,Q2-2046,Q2,2046-06-30,253,84733.47,1,interest_only,266.88,5,fix_to_float,11,SVR,0.0379,0.0359,NaN,2026-06-01,13.0

In [158]:
boe_extract.to_excel('/Users/andrewmcclymont/PycharmProjects/PythonProject/data/RMBS_Model/Python_Outputs/BoE_Extract.xlsx',
             sheet_name='BoE_Extract')